### PR TITLE
Added form validation

### PR DESCRIPTION
**Pull request by ticoniq**
### **Check if the email is lowercase**
Description: This pull request adds a check to make sure that email addresses are lowercase before they are submitted.

**Changes**

- Added form validation to the contact form.
- Added a check to make sure that email addresses are lowercase before they are submitted.
- Updated the CSS to display error messages.

### CODE REVIEW

**Review by Tufahel — CHANGES_REQUESTED** [review]
Hi @ticoniq, 👋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 

## Invalid Code Review Request

You have submitted a project, which is a pair programming activity where you and your partners everybody need to contribute to this project. But here I can see only your contribution. 😞 

According to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/9_validate_form.md), you should implement all the requirements in all repositories in your pair-programming group. That means that each group member needs to open a new pull request in their repo.

Before asking for any review kindly check the `Work and Submission` mode of that specific task. 🆗 
- ***Work and submission mode of this project:***
- image

Kindly make sure that your partners have participated with you in this activity and ask review again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ticoniq** [comment]
@Tufahel I worked with my partner on this but the project was too small for my partner to make any commit

**Comment by Tufahel** [comment]
> @Tufahel I worked with my partner on this but the project was too small for my partner to make any commit

@ticoniq, Sorry I can't help you in this regard. I only can judge your actions, such as `commit history`. In every pair-programming activity, there is a way to do it with your partner. Kindly go through your project/website/code again and I assure you, you will find some bugs or changes, where your partner can give input. Thanks and Happy Coding!!! 😃

**Comment by ticoniq** [comment]
> > @Tufahel I worked with my partner on this but the project was too small for my partner to make any commit
> 
> @ticoniq, Sorry I can't help you in this regard. I only can judge your actions, such as `commit history`. In every pair-programming activity, there is a way to do it with your partner. Kindly go through your project/website/code again and I assure you, you will find some bugs or changes, where your partner can give input. Thanks and Happy Coding!!! 😃

As I said earlier i and my partner worked on the code together, it was just 10 to 15 lines of code, and my partner could"nt make any commit

**Comment by ticoniq** [comment]
@Tufahel As I said earlier i and my partner worked on the code together, it was just 10 to 15 lines of code, and my partner could"nt make any commit

**Review by AbelG101 — APPROVED** [review]
# Hi @ticoniq & @henokkhm 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
