### PR TITLE
Portfolio - mobile menu

### PR DESCRIPTION
**Pull request by ticoniq**
### **Portfolio - mobile menu**

- Created the mobile menu
- Added mobile menu style
- Disable the scroll when the mobile is open
- Add even listener for clicking a mobile menu link

### CODE REVIEW

**Review by topeogunleye — COMMENTED** [review]
> Hi @ticoniq,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
## Invalid Code Review Request🛑 

>- [ ] Kindly update your linters.yml file for this project to include ESLinters. In the root project, you have a folder named .github. Inside this one, you have another folder named workflows. And inside the workflows folder, you have a file named linters.yml. Inside this file, you need to update the linters. The linters needed for this project can be found [here](https://github.com/microverseinc/linters-config/tree/master/html-css-js);

| Desp  | Images |
| ------------- | ------------- |
| Actions without ESLint  | image  |
| Actions with ESLint  | image  |

> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ticoniq** [comment]
@topeogunleye, please i need your help i just tried it and its still not working

**Comment by topeogunleye** [comment]
> > > @topeogunleye, please I need your help I just tried, and it's still not working 🙏🙏🙏
> > 
> > 
> > @ticoniq, did you update your linters workflow file?
> 
> Just to be sure how can I do that

You've done that. To update your linters.yml file. simply copy the content from the html-css-js linters workflow files and update your linters.yml file

image

**Review by Zuhaib042 — APPROVED** [review]
Hi @ticoniq 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Descriptive PR
✅ Professional Readme
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
